repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
        name: terraform fmt
        require_serial: true
      - id: terraform_tflint
        name: terraform lint
        require_serial: true
      - id: terraform_validate
        name: terraform validate
        entry: /bin/bash -c 'terraform init && terraform validate'
      - id: terraform_checkov
        name: checkov static code analysis
        args:
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yml
      #- id: infracost_breakdown
      - id: terraform_trivy
        name: trivy security scans
        args:
          - --hook-config=--parallelism-limit=1
          - --args=--skip-dirs=".terraform" --skip-dirs="wrappers" --skip-dirs="config"
      - id: terraform_wrapper_module_for_each
        name: create `for_each` wrapper module
        args:
          - --args=--module-dir=. # Process only root module
          #- --args=--dry-run # No files will be created/updated
          #- --args=--verbose # Verbose output
  # If you want to run tests on pre-commit
  #  - repo: local
  #    hooks:
  #      - id: terraform-test
  #        name: Terraform test
  #        language: system
  #        verbose: true
  #        require_serial: true
  #        entry: /bin/bash -c 'terraform test'
  - repo: local
    hooks:
      - id: terraform_docs
        name: terraform docs
        language: system
        verbose: true
        require_serial: true
        entry: /bin/bash -c 'terraform-docs markdown document -c .terraform-docs.yml .'
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
